---
docker_ok_version: "20.10.18"
supported_os: "{'Debian', 'CentOS', 'Rocky', 'Ubuntu'}"
supported_centos_ver: 8
supported_debian_ver: 10
supported_ubuntu_ver: 20

virtualenv_path: "{{ ansible_user_dir }}/.local/ubersmith_venv"

